name = raw_input("what is your name? ")
age = raw_input("how old are you? ")
f_color = raw_input("what is your favorit color? ")
f_food = raw_input("what is your favorit food? ")
f = open("user.txt",'w')
f.write(str(name)+"\n")
f.write(str(age))
f.write(str(f_color)+"\n")
f.write(str(f_food)+"\n")
f.close()
